name: My Portifolio Deploy

on:
  push:
    branches:
      - main

jobs:
  prod-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          sudo apt-get install -y awscli

      - name: Create SSH directory and known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Add AWS Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS Instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && ./my_portifolio.sh"